Submit shinooooo
ISC-MakeIT/javascript-100knocksV2 pull request #106
Opened 2019-07-17 13:40 UTC by shinooooo

js08~11

2019-07-18 14:58 UTC, fumihumi commented on answer/shinooooo/JS/08_createDiv/createDiv.html
> +      newDiv.style.cssText = 'height: 100px;'
この書き方をすると、 htmlに直接cssを記述する、いわゆるインラインスタイルになってしまいそうです。

styleタグを利用して、 特定のクラスに該当のStyleが反映されるようにしてみてください！

2019-07-18 14:58 UTC, fumihumi commented on answer/shinooooo/JS/09_switch/switch.html
> +      const Div = document.getElementById('image');
nits:変数名は大文字から始めるのではなく、小文字から始める場合がほとんどです！

2019-07-18 14:58 UTC, fumihumi commented on answer/shinooooo/JS/10_3sec/3sec.html
> +    Message = () => {
こちらもです 👀

2019-07-18 14:58 UTC, fumihumi commented on answer/shinooooo/JS/11_isSame/isSame.html
> +      }
```suggestion
    } else {
```
このように描くことがおおいです！

2019-07-19 05:39 UTC, shinooooo commented
指摘された箇所を修正しました！

2019-07-19 06:06 UTC, itti1021 requested changes
アロー関数に変更していていいですねぇ
ガンガン使って書き方身に着けてしまいましょう
微修正ですがよろしくお願いしますー:pray:

2019-07-19 06:06 UTC, itti1021 commented on answer/shinooooo/JS/08_createDiv/createDiv.html
> +    let i= 0;
```suggestion
    let i = 0;
```
ここスペース必要ですね～

2019-07-19 06:06 UTC, itti1021 commented on answer/shinooooo/JS/08_createDiv/createDiv.html
> +    createDiv = () => {
```suggestion
    const createDiv = () => {
```
アロー関数を定義する時は変数宣言をつけましょう:eyes:

2019-07-19 06:06 UTC, itti1021 commented on answer/shinooooo/JS/09_switch/switch.html
> +    change = () => {
ここもですー

2019-07-19 06:06 UTC, itti1021 commented on answer/shinooooo/JS/10_3sec/3sec.html
> +    message = () => {
ここｍ((

2019-07-19 06:06 UTC, itti1021 commented on answer/shinooooo/JS/11_isSame/isSame.html
> +    judge = () => {
こk((

2019-07-21 12:42 UTC, shinooooo commented
またひとつ賢くなりました！ありがとうございます

2019-07-22 00:32 UTC, shinooooo commented
修正した後に別の部分でエラーが出ないように書いた後見直しする癖をつけたいです...

2019-07-22 00:48 UTC, shinooooo commented
js12のエラーも出ておりますがとりあえず11までレビューお願い致します

2019-07-24 02:41 UTC, fumihumi commented on answer/shinooooo/JS/09_switch/switch.html
> +      const div = document.getElementById('image');
div タグにimageのIDつけると imgタグと混乱しちゃいそうですね。

2019-07-24 02:41 UTC, fumihumi commented on answer/shinooooo/JS/10_3sec/3sec.html
> +  const message = () => {
messageだと変数名っぽいニュアンス（品詞的に）, ですね、showAlert, showMessageみたいに、何をするための関数なのかわかるような命名だとよいかなと感じました。

2019-07-24 02:41 UTC, fumihumi commented on answer/shinooooo/JS/12_sumSquence/sumSquence.html
> +      console.log(`${sum}`);
sumだけ表示するなら変数展開(テンプレートリテラル)にする必要なさそうです

2019-08-09 10:31 UTC, fumihumi approved these changes

2019-08-09 10:31 UTC, fumihumi commented on answer/shinooooo/JS/07_addImage/addImage.html
> +      const addImage = `${value}'<img src="heavenstime.gif" alt= "画像">'`;
めっちゃ細かいですが。

valueってのが１つ前のinnerHTMLっていうことが少しわかりないかなと感じました。
僕なら valueではなく、prevInnerHTMLにして
```
prevInnerHTML + <img.....
もしくは
docum....getEl...Id(container).innerHTML += <img.
```

のように変数名でわかるように記述するか、`+=`を使って追加してることがわかるようにするかなと、

動いているので変更はしなくて大丈夫です👌

2019-08-09 10:31 UTC, merged