JS_1~4
ISC-MakeIT/javascript-100knocksV2 pull request #116
Opened 2019-08-07 00:19 UTC by tttkouyou

JSの１から４です。

2019-08-09 10:43 UTC, fumihumi reviewed
ほぼ全てのファイルにおいてですが、
定義した後に変更しない変数はconstにしてください。CIのエラーも確認してください

2019-08-09 10:43 UTC, fumihumi commented on answer/salami/Javascript/09_switch/09_switch.html
> +
ここだけ一行にしてるのはなぜだろう

2019-08-09 10:43 UTC, fumihumi commented on answer/salami/Javascript/10_3sec/10_3sec.html
> +    const denger = () => {
typo

2019-08-09 10:43 UTC, fumihumi commented on answer/salami/Javascript/11_isSame/11_isSame.html
> +        alert("Ture");
typo

2019-08-10 01:57 UTC, fumihumi reviewed
typoが多いですね。 spellcheckerの拡張機能とか入れるなりしてTypoしないように気をつけましょうか

2019-08-10 01:57 UTC, fumihumi commented on answer/salami/JS/01_wTime/01_wTime.html
> +
各行に空行を挟むと逆に読みにくくなるので、空行は処理の意図が変わる時など意味のある場合だけにしましょう

2019-08-10 01:57 UTC, fumihumi commented on answer/salami/JS/01_wTime/01_wTime.html
> +    const Clock = () => {
JavaScriptでは変数、関数名は lowerCamelCaseにすることが多いです

2019-08-10 01:57 UTC, fumihumi commented on answer/salami/JS/05_randomBgColor/05_randomBgColor.html
> +    const BC = () => {
BCだと意味が伝わらないのでもう少し、何をする関数なのか。わかる名前にしてみてください

2019-08-10 01:57 UTC, fumihumi commented on answer/salami/JS/05_randomBgColor/05_randomBgColor.html
> +  <button type="button" value="chenge" name="chenge" onclick="BC();">chenge</button>
typo: chenge

2019-08-10 01:57 UTC, fumihumi commented on answer/salami/JS/07_addImage/07_addImage.html
> +  <p><button type="button" onclick="chenge()">Image</button></p>
typo chenge

2019-08-10 01:57 UTC, fumihumi commented on answer/salami/JS/09_switch/09_switch.html
> +      switch (random) {
問題の本質とはずれますが、Caseがここまで多い場合は関数とかに分けたほうが読みやすいですね

2019-08-10 01:57 UTC, fumihumi commented on answer/salami/JS/14_storage/14_storage.js
> +  let a = window.sessionStorage.getItem('key');
a, bというような変数名ではなく、’なんの値が入ってるのか’がわかる変数名にしてみてください。

2019-08-10 01:58 UTC, fumihumi commented
あと、明らかにJS1~4ではなくなってるのでPRのタイトルとかも更新するように心がけてください

2019-08-10 09:00 UTC, tttkouyou commented on answer/salami/JS/09_switch/09_switch.html
> +      switch (random) {
ご指摘ありがとうございます。ですが、私には『関数とかに分ける』がうまく理解できませんでした。
できれば、例などを挙げてもらえると嬉しいです。不躾なお願いで申し訳ありません。

2019-08-10 11:37 UTC, fumihumi commented on answer/salami/JS/09_switch/09_switch.html
> +      switch (random) {
今回の例で言えば"image"じゃないidのものに画像を差し替えるように仕様変更が起きた時の修正箇所がかなり多くなりますよね？。
そう行った変更に耐えうるために同じ処理(記述)を関数にまとめた方が良いかなと感じました。

例えば↓みたいな感じです。
```
images = ［"aaa.png","bbb.png"］

setImage = (number) => dou...getEl...Id("xx").innerHTML = `任意の画像を出す感じに`

changeImage = () => 
    randNum = Math.floor(Math.random() * images.length) + 1;
    setImage(randNum)
```

こんな感じです。

まぁこれは気になっただけなので修正はしなくて大丈夫です。

2019-08-10 23:56 UTC, tttkouyou commented on answer/salami/JS/09_switch/09_switch.html
> +      switch (random) {
なるほど、わかりやすい説明をありがとうございます。きちんと理解することができました。これからはその考え方でコードを書いていこうと思います。

2019-08-13 12:57 UTC, fumihumi commented on answer/salami/JS/05_randomBgColor/05_randomBgColor.html
> +      random = Math.floor(Math.random() * 239) + 16;
これ再代入する必要ある？

2019-08-13 12:57 UTC, fumihumi commented on answer/salami/JS/05_randomBgColor/05_randomBgColor.html
> +      colorCode = `#${colorCode}${random.toString(16)}`;
これも２０行目と同じなきがする

2019-08-13 12:57 UTC, fumihumi commented on answer/salami/JS/06_bored/06_bored.css
> +  height: 100vh;
%とvhを使ってるけど、どっちも%とか、 vhとvwに揃えなかったのは何か意図がある？

2019-08-13 12:57 UTC, fumihumi commented on answer/salami/JS/06_bored/06_bored.html
> +      document.getElementById('bored').style.color = 'blue';
Styleを変えるために毎回Document.getEl...Idすると毎回Documentを捜査するので、

```
const boredElement = document.getEle...Id('xxx')
boredElement.innerHTML = 
boredElement.style.coloer = 
```
みたいに一度取得した要素に対してStyleを当てるようにしましょうか

2019-08-13 12:57 UTC, fumihumi commented on answer/salami/JS/07_addImage/07_addImage.html
> +      const addImg = document.getElementById('addImg').appendChild(img);
これ変数に入れる必要ある？

2019-08-31 14:09 UTC, fumihumi requested changes

2019-08-31 14:09 UTC, fumihumi commented on answer/salami/JS/06_bored/06_bored.html
> +      bored.innerHTML = 'AWESOME!';
should: これってブラウザのid属性の特性を使った暗黙の参照を使ってboredのプロパティを参照していますが、この方法はあまり使われないのでちゃんとJavascript側で selector経由で取得して取得したDOMに対して操作するようにしましょうか〜

2019-08-31 14:09 UTC, fumihumi commented on answer/salami/JS/22_rensouhairetu/22_rendouhairetu.html
> +    let ary = {
constでよさそう？

2019-08-31 14:09 UTC, fumihumi commented on answer/salami/JS/23_wather/23_wather.html
> +    let random = Math.floor(Math.random() * 4) + 0;
constでよさそう。 '0'を足すのは何か意図がありますか？

2019-08-31 14:09 UTC, fumihumi commented on answer/salami/JS/26_tanuki/26_tanuki.html
> +      } else if (sentence[i] === 'ふ') {
何もしないのにifで条件を書くと違和感がありますね？

2019-08-31 14:09 UTC, fumihumi commented on answer/salami/JS/29_dupDel/29_dupDel.html
> +        //Can'tのアポストロフィが引っかかってしまうので、ダブルコーテーションで対応しました。
commentがあると良いですね 👍

2019-08-31 14:09 UTC, fumihumi commented on answer/salami/jQuery/1_jquery/1_jquery.html
> +      if ($('#text').text() === 'Cosmos') {
javascirpt, jqueryどちらにおいてもですが,同じ要素に対して $('')やdocument.querySelectorのような検索系のDOMAPIを叩くとパフォーマンス的な観点であまりよくありません。
↓のように一度取得した DOM要素に対してメソッドを叩いてあげることでパフォーマンス的にも +1 なので今後はこういった観点も少し覚えておくと良いかもしれません〜

e.g.
```
const $text = $('#text')
$text.text() 
$text.xxx
```

2019-09-01 00:53 UTC, tttkouyou commented
ご指摘ありがとうございます。
そして、申し訳ありませんでした。期間が迫っていると思ってパニックになってしまい、やっていたすべてを上げてしまいました。
本来であれば、先輩に相談をして個別に出す方が最善でしたのに、冷静な判断が行えずにこのような事態になってしまいました。
本当に申し訳ありませんでした。

2019-09-01 01:00 UTC, fumihumi commented
いえいえ、こちらこそみるのが遅くなってしまいすみませんでした！
〆切に間に合っていることはとても大事なので、そのスタンスで大丈夫です🙆‍♀️

ひとまずお疲れ様でした！ 🚀 
修正に関しては神コンとの兼ね合いもあると思うので自分と相談してコメントの確認で終わっても大丈夫です👌

2019-09-01 01:29 UTC, tttkouyou commented
お気遣いありがとうございます。

2021-06-14 09:40 UTC, closed without merging