first push
ISC-MakeIT/javascript-100knocksV2 pull request #117
Opened 2019-08-07 06:19 UTC by shunshunISC

2019-08-21 07:44 UTC, shunshunISC commented
JavaScript-100knocksV2　１から3問目を解きました。
お願いします。

2019-08-31 13:57 UTC, fumihumi requested changes
htmlファイルを書く時は必ずDOCTYPE宣言やhtml, head, bodyタグといった基本的な構造を必ず書くようにしてください。

VScode標準のEmmetを使えば '!'を打つだけで必要なものが入力されます。
e.g. 

![](https://gyazo.com/ac109e9c279621bd742fb56dd652ca49.gif)

2019-08-31 13:57 UTC, fumihumi commented on answer/Otsu/HTML/02.anchor/anchor.html
> +    //-->
コメントアウトにしようとしたけど実際はコメントアウトになっていないような残骸は不要であれば削除しましょうか。

2019-08-31 13:57 UTC, fumihumi commented on answer/Otsu/HTML/03.form/form.html
> +<form name="form1" onSubmit="return check()">
タグが入れ子になる時は基本的にインデントをして下さい。

e.g
```
<div>
    <div>
        <p>hogehoge</p>
   </div>
</div>
```

2019-08-31 13:59 UTC, fumihumi commented on answer/Otsu/HTML/01.helloTable/helloTable.css
> +}
https://circleci.com/gh/ISC-MakeIT/javascript-100knocksV2/694?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
answer/Otsu/HTML/01.helloTable/helloTable.css
 1:8   ✖  Expected single space        block-opening-brace-space-before        
          before "{"                                                           
 2:5   ✖  Expected indentation of 2    indentation                             
          spaces                                                               
 2:24  ✖  Unexpected whitespace        declaration-block-semicolon-space-before
          before ";"
```
こちらも確認してみて下さい。

2021-06-14 09:40 UTC, closed without merging