修正Submit 166ryoryo
ISC-MakeIT/javascript-100knocksV2 pull request #123
Opened 2019-08-15 23:58 UTC by 166ryoryo

2019-08-18 01:20 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
>      function Random () {
[should] JavaScriptにおいて、関数は '小文字から始まる'風習が多いのでこの場合は `random()`の方が良さそうです 👀 

[imo] もっと言えば、'random'という関数名では なにをする関数なのか 名前から推測が難しいので generateRandomValueみたいな関数名からどんな結果がもらえるのかわかるような命名だとより良いかなと感じました

2019-08-21 00:54 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
>        return '#' + ('000000' + hex.toString(16)).substr(-6);
文字列の結合にはteplateリテラルを使いましょうか〜

2019-08-21 00:54 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    henkou.addEventListener ('click', function () {
[should] 無名関数を使うときはArrowFunctionの方がBetter

```
  19:39  error    Unexpected function expression                      prefer-arrow-callback
```

e.g.
```javascript
xxx.addEventListener('xxx', () => {
    console.log('this is callback function!');
});

```

2019-08-21 00:54 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    function randomcolor () {
細かいですが、

細かいですが
```
  19:12  error    Unexpected newline between function name and paren  func-call-spacing
  19:12  error    Unexpected space between function name and paren    no-spaced-func
 ```

このへんも確認してみてください

2019-08-25 23:41 UTC, 166ryoryo commented
修　２８まで

2019-08-31 13:52 UTC, fumihumi requested changes
総じて、弊学の授業ではなぜかローマ字読みの変数名を使いますが、実際にプログラムを組む際はそんな変数名まずつけないので可能な限り英単語を利用し、変数名をみればその変数になんの値が入っているかわかるような命名を気にできるよより読みやすくなるなと感じました。

2019-08-31 13:52 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +      return `#${(`000000` + hex.toString(16)).substr(-6)}`;
> `#${(`000000` + hex.toString(16)).substr(-6)}`;
ここって文字列の '000000'とhex.toString...を足し算したいのですか？ それとも数値と足し算をしようとしてますか？？
数値であればこの "` (バッククォート)"は不要な気がします 👀 

あと バッククォートで囲っている文字列の中で文字列を定義する時はシングルクォートを使った方が読みやすい気がしました 👀 

--------------------
ちなみにここってどうして '000000'と連結してるのだろう。
> hex.toString(16)).substr(-6)

これだけでも良いような気がする？

2019-08-31 13:52 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    henkou . addEventListener ('click', () => {
> henkou . addEventListener

これだと動かない気がする

2019-08-31 13:52 UTC, fumihumi commented on answer/166ryoryo/JS/10/3sec.html
> +    document.getElementById('btn').onclick = function(a){
ここに引数で渡している `a`は本当にひつようですか ?

2019-08-31 13:52 UTC, fumihumi commented on answer/166ryoryo/JS/24/encrypto1.js
> +// eslint-disable-next-line no-unused-vars
このdisable-xxxは必要ですか？

2019-08-31 13:52 UTC, fumihumi commented on answer/166ryoryo/JS/27/duplicate.js
> +const li = p(1, 75, 25);
"p"という関数名は何かの略語でしょうか。正直何も伝わらないので関数の挙動がわかるような関数名をつけるようにしましょうか 👀

2019-08-31 13:52 UTC, fumihumi commented on answer/166ryoryo/JS/30/partoftable.html
> +      let randoms = Math.floor(Math.random() * 75) + 1;
randomsという複数系なのに中に入っている値は単数なのはちょっと違和感ありますね

2021-06-14 09:40 UTC, closed without merging