second
ISC-MakeIT/javascript-100knocksV2 pull request #134
Opened 2021-06-16 08:40 UTC by kentyisapen

HTMLの2番を解きました。
採点お願いします

2021-06-16 08:43 UTC, s61t6ftaro-sab requested changes, later dismissed

2021-06-16 08:43 UTC, s61t6ftaro-sab commented on answer/KENKENBAKA/HTML/index.html
> +    <a href="https://isc-makeit.github.io/Make-IT-homepage/" onclick="open">リンク</a>
jsではなくaタグが先に動いちゃってますね💦

2021-06-24 07:40 UTC, s61t6ftaro requested changes

2021-06-24 07:40 UTC, s61t6ftaro commented on answer/KENKENBAKA/HTML/1_helloTable.html
> +        <tr><td>こんにちは</td><td>こんにちは</td></tr>
問題ないよ～〇

インデント的にはこっちの方いいかな
```
<tr>
  <td rowspan="3">こんにちは</td>
  <td>こんにちは</td>
  <td>こんにちは</td>
</tr>
<tr>
  <td>こんにちは</td>
  <td>こんにちは</td>
</tr>
<tr>
  <td>こんにちは</td>
  <td>こんにちは</td>
</tr>
```

2021-06-24 07:41 UTC, s61t6ftaro approved these changes

2021-06-24 07:45 UTC, s61t6ftaro requested changes

2021-06-24 07:45 UTC, s61t6ftaro commented on answer/KENKENBAKA/HTML/3_form.html
> +            <option value="0">0</option>
ここ力業で0－200タグ書くより**jsで0-200のタグを作る**っていう処理を書いたほうがいいね

2021-06-24 07:51 UTC, s61t6ftaro commented on answer/KENKENBAKA/HTML/index.html
>              window.open("https://isc-makeit.github.io/Make-IT-homepage/");
いいね！問題ないよ

細かい所だと見栄えがテキストっぽいからリンクに見えるようにしたらいいね
※変更してもしなくてもOKです

2021-06-24 07:54 UTC, s61t6ftaro requested changes

2021-06-24 07:54 UTC, s61t6ftaro commented on answer/KENKENBAKA/HTML/2_anchor.html
>      </script>
いいね！問題ないよ

細かい所だと見栄えがテキストっぽいからリンクに見えるようにしたらいいね
※変更してもしなくてもOKです

2021-06-24 07:54 UTC, s61t6ftaro commented on answer/KENKENBAKA/HTML/1_helloTable.html
> +    </table>
HTML2番OK～問題ないよ～

インデント的にはこっちの方いいかな

```
<tr>
  <td rowspan="3">こんにちは</td>
  <td>こんにちは</td>
  <td>こんにちは</td>
</tr>
<tr>
  <td>こんにちは</td>
  <td>こんにちは</td>
</tr>
<tr>
  <td>こんにちは</td>
  <td>こんにちは</td>
</tr>
```

2021-06-24 07:56 UTC, s61t6ftaro commented
レビューアーに**s61t6f**の追加お願いします。
サブを入れてるので・・・・ややこしくてすません

2021-06-25 02:00 UTC, yukiy4n4g1 commented on answer/KENKENBAKA/HTML/1_helloTable.html
> +    <table border="1"  bordercolor="red">
直さなくてもいいけど、`border`と`bordercolor`属性は非推奨だから次からはCSSでやってくれると👍
参考:https://developer.mozilla.org/ja/docs/Web/HTML/Element/table#attributes

2021-06-25 12:51 UTC, merged