CSS4 修正版
ISC-MakeIT/javascript-100knocksV2 pull request #147
Opened 2021-10-16 08:47 UTC by AYATSUKO

画像フォルダを問題と同じディレクトリに移動させました。これで大丈夫でしょうか？
vscodeで、保留中の変更の欄に画像のファイルが表示されていました。なので間違ってるのか・・と思いながらも一応出すことにします。

2021-10-20 08:06 UTC, s61t6ftaro requested changes

2021-10-20 08:06 UTC, s61t6ftaro commented on blackrock/onimage.html
> +        <img src="C:\Users\n1210470.STCN2\Desktop\program warehouse\javascript-100knocksV2\img containment\cross dead material.jpg" width="472" height="472" alt="flont">
画像表示のパスを絶対パスを使ってるのは問題ないんだけれど、これよりももっと短くかける相対パスで修正してみようか
※絶対パスだと元がローカル（その人）の手元に画像があってgithubから見れないからっていう点でも相対パスで書いてほしい

もし絶対パス相対パスわからない場合はググってもろて、そんな難しくないので
相対パスの場合例えば、問題ファイル/回答ファイルがある階層かその近くにimg画像入れる
gitにpushするときそのディレクトリも入れる（add commit push)

階層例：
- javascript-100nocksV2
  - blackrock
  - source
    - img ←ここにいれる

2021-10-20 11:32 UTC, AYATSUKO commented on blackrock/onimage.html
> +        <img src="C:\Users\n1210470.STCN2\Desktop\program warehouse\javascript-100knocksV2\img containment\cross dead material.jpg" width="472" height="472" alt="flont">
これでどうでしょうか。画像もコードと同時にコミット＆プッシュしておきました。

2021-10-20 12:30 UTC, s61t6ftaro approved these changes
問題ないよ～

2021-10-20 12:30 UTC, s61t6ftaro commented on blackrock/onimage.html
> +        <img src="..\img containment\cross dead material.jpg" width="472" height="472" alt="flont">
しっかり相対パスでもってこれてるね！

あとディレクトリ名がいま「img containment」になってるとおもうんだけど単語の間を半角で開けることはあまりないので「_」や「-」か「imgContainment」頭文字を大文字にしたりしたほうがいいかな

2022-03-10 02:29 UTC, s61t6ftaro approved these changes
ペアプロやICONのあとだからやっぱり綺麗に書けてるね。問題ないよ～

2022-03-10 02:30 UTC, merged