HTML2もんめです
ISC-MakeIT/javascript-100knocksV2 pull request #23
Opened 2019-05-30 01:02 UTC by luke2074

2019-05-30 08:43 UTC, feketerigo222 requested changes
2つ目のリンク、クリックするたびにその都度新しいタブで開くようにしてみてください。

2019-05-31 01:49 UTC, haduki1208 requested changes
タブは直ってました。OKです。
要素の修正お願いします。

2019-05-31 01:49 UTC, haduki1208 commented on answer/luke2074/HTML2.html
> +    </a>
インラインレベルの要素(aタグ)の中にブロックレベルの要素(pタグ)を入れないようにしましょう。

2019-05-31 08:27 UTC, haduki1208 requested changes
修正をお願いします。

2019-05-31 08:27 UTC, haduki1208 commented on answer/luke2074/HTML2.html
> +    </a>
htmlは入れ子構造になるようにしましょう。
<p><a></p></a>はNGです。

2019-06-03 02:17 UTC, haduki1208 approved these changes
OKです

2019-06-03 02:18 UTC, merged