100nocks
ISC-MakeIT/javascript-100knocksV2 pull request #30
Opened 2019-05-30 07:54 UTC by 166ryoryo

2019-05-30 08:50 UTC, haduki1208 commented on 100nocks 166ryoryo/CSS/centerDiv.html
> +            </div>
インデントを整えましょう

2019-05-30 08:53 UTC, haduki1208 commented on 100nocks 166ryoryo/HTML/anchor.html
> +            function openWin() {
openWindowの方がわかりやすくていいと思います

2019-05-30 09:04 UTC, haduki1208 commented on 100nocks 166ryoryo/HTML/hello Table.html
> +<!DOCTYPE html>
ファイル名にスペースを入れないようお願いします。helloTableのように繋がる単語の先頭を大文字にする方法、hello_tableのように_(アンダーバー)で繋げる方法があります。

2019-05-30 09:04 UTC, haduki1208 requested changes
ファイル名の変更が必須です。

2019-05-30 09:22 UTC, 166ryoryo commented
修正とcssの途中経過

2019-05-30 09:48 UTC, haduki1208 requested changes
```
<div>
    <p>
        <span>
        </span>
    </p>
</div>
```
のようにきれいな階層になるようにしてみてください。

2019-05-30 09:48 UTC, haduki1208 commented on 100nocks166ryoryo/CSS/centerDiv.html
> +</div>
階層構造にしてみましょう

2019-05-30 09:48 UTC, haduki1208 commented on 100nocks166ryoryo/CSS/shadow.html
> +</body>
階層構造にしてみましょう

2019-05-31 08:32 UTC, haduki1208 requested changes
https://github.com/ISC-MakeIT/javascript-100knocksV2/blob/master/answer/example/%E5%9B%9E%E7%AD%94%E6%89%8B%E9%A0%86.md
を参考に問題ごとにフォルダを切ってください。ソースコードは問題ないです。

2019-06-03 02:22 UTC, haduki1208 approved these changes
OKです

2019-06-03 02:23 UTC, merged