Submit damegane
ISC-MakeIT/javascript-100knocksV2 pull request #34
Opened 2019-05-31 01:43 UTC by DuGlaser

HTML終わりました

2019-05-31 01:55 UTC, haduki1208 requested changes
修正お願いします

2019-05-31 01:55 UTC, haduki1208 commented on answer/damegane/HTML/03/03.html
> +          <input type="radio" name="sex" value="女">女</td>
labelタグを使って文字をクリックしてもチェックがつくようにしましょう

2019-05-31 01:55 UTC, haduki1208 commented on answer/damegane/JS/15/15.html
> +      //document.write(count);
使わない処理・コメントは削除しましょう

2019-06-03 02:26 UTC, haduki1208 commented
コメントをした箇所の修正をしてください。

2019-06-04 04:49 UTC, fumihumi reviewed
全体的に’不要な改行’と’インデントのズレ’がめだちます！今一度、確認してください！

2019-06-04 04:49 UTC, fumihumi commented on answer/damegane/CSS/02.shadow/02.css
> +height:200px;
indentを入れるようにしましょう 👀

2019-06-04 04:49 UTC, fumihumi commented on answer/damegane/CSS/01.centerDiv/01.css
> +  margin:0 auto;
CSSにおいて、 ':'のあとは半角スペースを入れましょうか！

2019-06-04 04:49 UTC, fumihumi commented on answer/damegane/CSS/01.centerDiv/01.html
> +
```suggestion
```
この空行は不要そうです 👀

2019-06-04 04:49 UTC, fumihumi commented on answer/damegane/CSS/02.shadow/02.html
> +  <link rel="stylesheet" href="02.css">
styleタグでなくlinkを使っていて良いです 👍

2019-06-04 04:49 UTC, fumihumi commented on answer/damegane/CSS/03.nav/03.css
> +
😭

2019-06-04 04:49 UTC, fumihumi commented on answer/damegane/CSS/03.nav/03.html
> +  <p class="btn top">Top</p>
[修正は不要] 動作はしているので問題ないのですが、

こういった、要素それぞれが意味を成す塊の場合

ul, liタグを使うと良いなぁと感じました 👀

2019-06-04 04:49 UTC, fumihumi commented on answer/damegane/HTML/03.form/03.html
> +            <option>200</option>
ありがとうございます 🙇

2019-06-04 04:49 UTC, fumihumi commented on answer/damegane/HTML/03.form/03.html
> +          <label><input type="radio" name="sex" value="女">女</label></td>
```html
       <td>
          <label><input type="radio" name="sex" value="男">男</label>
          <label><input type="radio" name="sex" value="女">女</label>
      </td>
```

改行を入れる場合は入れ子構造が見えるようにいしきするとよいですね〜

2019-06-18 05:52 UTC, fumihumi reviewed
少し細かい指摘がありますが、確認お願いします 👀

2019-06-18 05:52 UTC, fumihumi commented on answer/damegane/CSS/02.shadow/02.css
> +  background-color: green
```suggestion
  background-color: green;
```

semicolon~~~ 😭

2019-06-18 05:52 UTC, fumihumi commented on answer/damegane/CSS/06.float/06.html
> +
nits 👀 
```suggestion
```

2019-06-18 05:52 UTC, fumihumi commented on answer/damegane/CSS/08.grid/08.html
> +      <p id="detail">新刊発売</p>
💯

2019-06-18 05:52 UTC, fumihumi commented on answer/damegane/JS/15/15.html
> +      else if (x === 0) {
[should]

x,y,zと `変数に入れる` のはとても良いことですが、変数名が 'x'だと何を示しているのか’パッと見でわからなくなってしまいます....’
e.g: DivisedByThree, 
のように’どんな値が入っているのか’がわかる変数名にできるともっと良いかなと！ 👍

2019-06-18 05:52 UTC, fumihumi commented on answer/damegane/JS/15/15.html
> +
細かいですが.......
```suggestion
```

2019-06-19 00:35 UTC, feketerigo222 commented on answer/damegane/CSS/10.drawing/10.html
> +</html>
凄い…凄いんだけどもっと気楽に作っていいよ

2019-06-19 03:50 UTC, feketerigo222 requested changes

2019-06-19 03:50 UTC, feketerigo222 commented on answer/damegane/CSS/06.float/06.html
> +</html>
これも一つの正解ですが、07.flexboxのようにHTML上では123456の順に並ぶようにしてみてくださいm(_ _)m

2019-06-30 06:42 UTC, fumihumi commented on answer/damegane/HTML/02.anchor/02.html
> +  <p><a href="https://isc-makeit.github.io/Make-IT-homepage/" target="_blank">Make IT(新規タブ)</a></p>
target blankの時は relオプションもつけるように意識してください 👀 

fyi: https://qiita.com/memolog/items/9913b0067e4e6883ed17

2019-06-30 06:42 UTC, fumihumi commented on answer/damegane/JS/01.wTime/01.html
> +        value = '0' + value;
`JavaScriptの暗黙の型変換` でぐぐると結構出てくるんですが、
文字列 '0' と 数値 'value'を足し算するのはバグの温床になりがちです。

文字列の連結を行いたい際は、明示的に `数値を文字列`に変換した上で繋げるようにしましょう 👀

2019-06-30 06:42 UTC, fumihumi commented on answer/damegane/JS/15.fizzbuzz/15.html
> +      let fizz = count % 3;
変数の内容が変わることがない場合はconstのが良いですね

2019-06-30 06:42 UTC, fumihumi commented on answer/damegane/JS/02.add/02.html
> +      document.write('<p>' + value++ + '</p>');
document.write以外の方法で動かすようにしてみてください〜
これは非推奨になっています。

2019-06-30 12:42 UTC, fumihumi commented
> https://circleci.com/gh/ISC-MakeIT/javascript-100knocksV2/246?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

あともう少し(?)なのでこちらのエラー対応もお願いします！ 💪

2019-06-30 23:45 UTC, fumihumi commented
対応ありがとうございます！
jsの"no_unused_var"は今回対応しちゃうとダメな気がするのでこのままで大丈夫です、

2019-06-30 23:46 UTC, fumihumi approved these changes

2019-06-30 23:47 UTC, merged