HTML3問目です
ISC-MakeIT/javascript-100knocksV2 pull request #39
Opened 2019-05-31 06:01 UTC by tsunakan0o0

2019-05-31 08:40 UTC, yamato3310 commented
javascriptも使っていていいと思います
あとidがeeeのところがあったので次回以降分かりやすいid名がつけられるといいと思います

2019-05-31 08:45 UTC, haduki1208 requested changes
修正をお願いします。

2019-05-31 08:45 UTC, haduki1208 commented on answer/tsunakan0o0/HTML3.html
> +        <p> <h1>name:</h1><br><input type="text" name="NAME" required placeholder="Ymada　Taro"></p>
h1タグはサイト内に複数配置するようなタグではないので別の要素に置き換えてください。

2019-05-31 08:45 UTC, haduki1208 commented on answer/tsunakan0o0/HTML3.html
> +                   <input type="radio" name="sex" value="1" required>female
labelタグを使って文字をクリックしてもチェックできるようにしてください。

2019-06-03 02:28 UTC, haduki1208 approved these changes
一応OKです。fontタグは次回から使わないようにしてください。

2019-06-03 02:28 UTC, merged