HTML2問目です
ISC-MakeIT/javascript-100knocksV2 pull request #41
Opened 2019-05-31 09:12 UTC by zamadokaSchool

2019-05-31 09:17 UTC, haduki1208 requested changes
DOMはきれいにかけてます。修正お願いします。

2019-05-31 09:17 UTC, haduki1208 commented on zamadokaSchool/HTML2/HTML2.html
> +<html>
htmlファイルは
```
<html>
    <head>
    </head>
    <body>
    </body>
</html>
```
で構成するようにお願いします。

2019-05-31 09:17 UTC, haduki1208 commented on zamadokaSchool/HTML2/HTML2.html
> +    <label>
labelタグで囲わなくても大丈夫です。

2019-06-03 06:41 UTC, zamadokaSchool commented
HTML2問目修正しました

2019-06-04 04:39 UTC, fumihumi approved these changes
よさそうです 🙆

2019-06-04 04:39 UTC, merged