HTML3問目
ISC-MakeIT/javascript-100knocksV2 pull request #47
Opened 2019-06-04 09:30 UTC by zamadokaSchool

2019-06-04 09:55 UTC, fumihumi requested changes

2019-06-04 09:55 UTC, fumihumi commented on zamadokaSchool/HTML3/HTML3.html
> +                <input type="password" id="password" name="password" placeholder="p@ssw0rd">
適切なtypeが指定されていて良いですね 👍

2019-06-04 09:55 UTC, fumihumi commented on zamadokaSchool/HTML3/HTML3.html
> +                <script>
scriptタグはhtmlの途中に置けますが、置く場合は
</body>のすぐ上か、<head>タグの中に置くようにしましょう！

2019-06-04 09:55 UTC, fumihumi commented on zamadokaSchool/HTML3/HTML3.html
> +                        }
js頑張ってくださりありがとうございます...... 🙇 

以下の箇所を修正してもらいたいです 🙏 
```javascript
const selectElement = document.getElementById("age");
for(let i = 0; i <= 200; i ++){
  const option = document.createElement("option"); 
```

詳しい理由を少し省略しますが、
基本的にjavascirptの変数宣言においては `var`は’もう’使いません。(数年前に新しい構文が作成されたため。)
そのため↑のスクリプトにある `var`の記述を `const`, or `let`に置き換えて欲しいです 🏹 

(ここではhtmlの問題のため解答を伝える形にしました cc reviewers)

2019-06-04 09:55 UTC, fumihumi commented on zamadokaSchool/HTML3/HTML3.html
> +                        function age() {
[in my opinion](jsへの指摘ですみません...)
関数名 `age`だと '年齢'という関数名になってしまい少々意図が伝わりにくいかなとかんじました 🤔 

ここでやりたいことは select直下にoptionタグの追加をしたいためそれが伝わるような関数名だとより良いのかなと感じました

e.g. 
- function createAgeOptionTagsToAgeSelector() {}
- function createAgeOptionElementsToAgeSelector()

2019-06-04 09:55 UTC, fumihumi commented on zamadokaSchool/HTML3/HTML3.html
> +                <input type="radio" value="Male" name="sex" >Male
'Male'をクリックした時もradioボタンがきくようにlabelタグ等を用いてみてください！

2019-06-05 08:55 UTC, zamadokaSchool commented
HTML3問目修正しました。
- scriptタグを</body>のすぐ上に移動
- `var`を`let`に置換
- 関数名を`createAgeOptionTagsToAgeSelector`に変更
- `Male`をクリックしたときもradioボタンがきくように修正

2019-06-06 02:35 UTC, fumihumi approved these changes
修正内容をコメントしてくださりありがとうございます！良さそうです！

2019-06-06 02:35 UTC, merged