Submit shinooooo
ISC-MakeIT/javascript-100knocksV2 pull request #51
Opened 2019-06-05 08:58 UTC by shinooooo

自動化テストです

2019-06-06 02:33 UTC, fumihumi commented
circleCIというサービスでコードの正規化をしているんですが、そちらのサービスにgithubでログインすると↓のリンクが踏めるようになると思います。

> https://circleci.com/gh/ISC-MakeIT/javascript-100knocksV2/57?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

すると
```
answer/shinooooo/HTML/03_form/form.html: line 22, col 16, line contains trailing whitespace
answer/shinooooo/HTML/03_form/form.html: line 10, col 11, attribute values cannot be empty
answer/shinooooo/HTML/03_form/form.html: line 12, col 14, the `style` attribute is banned
answer/shinooooo/HTML/03_form/form.html: line 15, col 14, the `style` attribute is banned
answer/shinooooo/HTML/03_form/form.html: line 18, col 14, the `style` attribute is banned
```

のようにファイルのどこを直して欲しいのかが書いてあるのでそちらを確認してもらえますでしょうか 👀

2019-06-06 02:37 UTC, shinooooo commented
了解しました！ご教授ありがとうございます

2019-06-06 02:48 UTC, fumihumi commented
不明点あれば改めて連絡ください~ 🙇

2019-06-10 00:39 UTC, shinooooo commented
エラーについて調べたり修正したんですけど残ってるエラーの解消法が分かりません...

2019-06-10 13:06 UTC, fumihumi requested changes

2019-06-10 13:06 UTC, fumihumi commented on answer/shinooooo/HTML/03_form/form.html
> +        <p><label><input type="radio" name="sex" checked="checked" id="male">male</label>
```suggestion
        <p>
            <label><input type="radio" name="sex" checked="checked" id="male">male</label>
```
入れ子が視覚的にわかるとよいかなと〜

2019-06-10 13:06 UTC, fumihumi commented on answer/shinooooo/HTML/03_form/form.html
> +                document.write('<option value="+i+">'+i+'</option>');
なぜか授業では`document.write`を利用していますが。これはすでに非推奨とされています。
refs: http://blog.3streamer.net/html5-css3/document-write-html5-181/

そのため、今回の場合は、
document.querySelector , createElement, appendChild
といったような関数を使う方がより良いのかなとおもいます！

※これはHTMLの問題のためここでは修正しなくて大丈夫ですが、今後 `document.write`は使わないように心がけてみてください

2019-06-10 13:34 UTC, shinooooo commented on answer/shinooooo/HTML/03_form/form.html
> +                document.write('<option value="+i+">'+i+'</option>');
了解しました！

2019-06-10 13:46 UTC, shinooooo commented
入れ子のインデント修正しました

2019-06-10 14:00 UTC, fumihumi approved these changes
thanks

2019-06-10 14:00 UTC, merged

2019-06-10 14:01 UTC, shinooooo commented
こちらこそ丁寧な対応ありがとうございます！