Submit isshun226
ISC-MakeIT/javascript-100knocksV2 pull request #53
Opened 2019-06-05 14:27 UTC by isshun226

2019-06-06 02:26 UTC, fumihumi commented
ぬっはコミットログがえぐいことになってる
（各問でコミットしてるから一応はレビューしやすいがw）

2019-06-13 09:18 UTC, feketerigo222 requested changes

2019-06-13 09:18 UTC, feketerigo222 commented on answer/isshun226/CSS/7/flexbox.html
> +</html>
flexboxの使い方は正しいので、例題のようにhtmlファイルとは逆順に並ぶようにしてみてください

2019-06-13 09:18 UTC, feketerigo222 commented on answer/isshun226/CSS/8/CSSgrid.html
> +</html>
正解だけど絵面がとても汚いです。

2019-06-13 22:29 UTC, fumihumi commented
js問題のciがほぼ全ての問題でこけてるので確認してくださいー

2019-06-28 09:13 UTC, fumihumi commented
48641c7

これなんでディレクトリいどうしてるんだ 👀

2019-07-02 14:24 UTC, isshun226 commented
ディレクトリ間違えて消してpullして戻そうと思ったらディレクトリが2つになってたので片方消しました

2019-07-02 14:33 UTC, fumihumi commented
それ消すディレクトリ間違えてる気がする

2019-07-02 14:35 UTC, isshun226 commented
消したと思ったらドラッグで移動してただけっていうオチなので特に他のディレクトリ消したってことはないです！説明足りてませんでした申し訳ないです

2019-07-02 14:50 UTC, fumihumi commented
```diff
- answer/example/isshun226/**/*
+ answer/isshun226/**/*
```

正しくはこういうディレクトリ構成のため、こうなるように移動お願いします〜

2019-07-02 14:52 UTC, isshun226 commented
今error読んでて直そうとしてました！これってファイルの位置間違ってて参照できてないからerrorはいてるってことですよね？

2019-07-02 14:52 UTC, fumihumi commented
> これってファイルの位置間違ってて参照できてないからerrorはいてるってことですよね？

そういうことです〜

2021-06-14 09:40 UTC, closed without merging