Submit shinooooo
ISC-MakeIT/javascript-100knocksV2 pull request #70
Opened 2019-06-15 13:54 UTC by shinooooo

css4~7です

2019-06-15 18:37 UTC, feketerigo222 requested changes
ごめんなさい。面倒くさいかもしれませんが、6問目はfloatを使って書いてください。

2019-06-17 13:05 UTC, shinooooo commented
floatを使って解き直しました！

2019-06-17 16:36 UTC, feketerigo222 requested changes

2019-06-17 16:36 UTC, feketerigo222 commented on answer/shinooooo/CSS/06_float/float.css
> +  display: flex;
何度も申し訳ない。flexboxを使わないで、floatだけで書いてみて！

2019-06-18 02:03 UTC, shinooooo commented
何度もすいません...

2019-06-18 02:18 UTC, merged

2019-06-18 02:18 UTC, feketerigo222 commented
OKです