Submit shinooooo
ISC-MakeIT/javascript-100knocksV2 pull request #76
Opened 2019-06-20 03:50 UTC by shinooooo

css8~9です

2019-06-20 04:14 UTC, feketerigo222 requested changes

2019-06-20 04:14 UTC, feketerigo222 commented on answer/shinooooo/CSS/08_CSS_Grid/CSS_Grid.html
> +</html>
全体的に良くできていますが、imgタグではなくbackground-imageでbackground-size: coverを使う、font-sizeを75pxくらいにするとグッと見栄えが良くなります。

2019-06-20 04:33 UTC, feketerigo222 commented on answer/shinooooo/CSS/08_CSS_Grid/CSS_Grid.html
> +</html>
ごめんなさい。imgタグでもfont-sizeを抑えるだけで大丈夫ですね。

2019-06-20 05:08 UTC, shinooooo commented on answer/shinooooo/CSS/08_CSS_Grid/CSS_Grid.html
> +</html>
ありがとうございます！弄ってみます

2019-06-21 00:38 UTC, shinooooo commented
background-imageも使える事を理解しました

2019-06-21 03:56 UTC, merged

2019-06-21 04:03 UTC, s61t6ftaro commented
*{
	padding: 0;
	margin:0;
	box-sizing: border-box;
}
これCSSに入れると隙間消すことできるよ