Submit 166ryoryo
ISC-MakeIT/javascript-100knocksV2 pull request #80
Opened 2019-06-21 06:05 UTC by 166ryoryo

2019-06-21 08:42 UTC, s61t6ftaro reviewed
前の状態であってるよ💦

2019-06-24 06:42 UTC, feketerigo222 requested changes
インデントについても統一してもらえるとありがたいです

2019-06-24 06:42 UTC, feketerigo222 commented on 100nocks166ryoryo/HTML/03/form.html
>              <input type="radio"  name="sex" value="Female"required>Female
labelを利用して、Male/Femaleの文字をクリックしても選択できるようにしてみてください

2019-06-25 00:31 UTC, feketerigo222 requested changes

2019-06-25 00:31 UTC, feketerigo222 commented on 100nocks166ryoryo/JS/07/addImage.html
> +</html>
bodyからのインデントも半角スペース2個で統一するとさらに見栄えが良くなるかと。一度新しい問題を解くのをやめて、傷が浅いうちに既に解いた問題のインデントを全部直さないとずっとCIでエラーが出るかと思われます。<SCRIPT>や<FORM>等のタグも小文字でお願いします。修正次第、一旦マージします。

2019-06-25 02:25 UTC, feketerigo222 requested changes
細かくなってしまいますが、関数内でもインデントをお願いします。

2019-06-25 02:25 UTC, feketerigo222 commented on 100nocks166ryoryo/JS/05/randomBgColor.html
> +</SCRIPT>
；お願いします

2019-06-25 02:25 UTC, feketerigo222 commented on 100nocks166ryoryo/JS/05/randomBgColor.html
> +  </FORM>
<script>と<form>は小文字で

2019-06-25 02:25 UTC, feketerigo222 commented on 100nocks166ryoryo/JS/06/bored.html
> +  <script>document.getElementById("text-button").onclick = function() {
改行して欲しいです

2019-06-30 06:36 UTC, fumihumi commented on answer/166ryoryo/HTML/01/hello_Table.html
> +    <th>こんにちは</th>
thはheaderの意味を持つので２行目いこうはthじゃない方がよいかな 👀

2019-06-30 06:36 UTC, fumihumi commented on answer/166ryoryo/HTML/02/anchor.html
> +    function openWin() {
```suggestion
    function openWin() {
        window.open(
            "https://isc-makeit.github.io/Make-IT-homepage/",
            "_blank",
            "menubar=0,
            width=300,
            height=200,
            top=200,
            left=200"
        );
    }
```
インデント気をつけましょう 👀 
カンマで改行するなら全部改行した方が統一感がありそうですね

2019-06-30 06:36 UTC, fumihumi commented on answer/166ryoryo/JS/01/wTime.html
> +    setInterval('showClock1()',1000);
nits

```suggestion
    setInterval('showClock1()', 1000);
```

2019-06-30 06:36 UTC, fumihumi commented on answer/166ryoryo/JS/08/createDiv.html
> +        aaa =()=> {
関数名には意図を持たせましょう。 `aaa` だと何をしたいのか伝わってきません 😭 
e.g. `createDivElement`

また、Arrow関数での定義の場合は変数定義と同様に`const`キーワードもつかいましょう!

2019-06-30 06:36 UTC, fumihumi commented on answer/166ryoryo/JS/07/addImage.html
> +    let zoon = document.getElementsByClassName('p');
indent.........

2019-07-02 14:51 UTC, fumihumi commented
CIエラーでわからないところとかあったらその旨お伝えください〜

2019-07-02 14:59 UTC, fumihumi requested changes
CIエラーが溜まって大変だとは思いますが、コツコツお願いします.......

2019-07-02 14:59 UTC, fumihumi commented on answer/166ryoryo/JS/11/isSame.html
> +            if (text1 && text2) {
nits

```suggestion
            if (text1とtext2のどっちか(もしくは双方)が空の時) { return }

            if (text1 === text2) {
              alert('true');
            } else {
              alert('false');
            }
```

みたいに書くと `if`のネストが浅くなって個人的に好きでsu

2019-07-02 14:59 UTC, fumihumi commented on answer/166ryoryo/JS/09/switch.html
> +                    let Img = document.getElementById('tantei');
nits: 
javascriptでは`変数`の命名の際に '小文字から始まる'変数名が多いです。 
(正確にいうと'lowerCamelCase'..)

FYI: http://cou929.nu/data/google_javascript_style_guide/#id28

2019-07-02 14:59 UTC, fumihumi commented on answer/166ryoryo/JS/08/createDiv.html
> +        <input type="button" value="fueru" onclick="hako()">
indent 👀

2019-07-02 14:59 UTC, fumihumi commented on answer/166ryoryo/JS/06/bored.html
> +  <script>document.getElementById("text-button").onclick = function() {
```suggestion
  <script>
    document.getElementById("text-button").onclick = function() {
```
みたいに改行したみ

2019-07-02 14:59 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +<script LANGUAGE="JavaScript">
ちょっと指摘事項が多そうなのでCIのエラーの修正を優先してください〜

2019-07-03 14:37 UTC, itti1021 requested changes
ciのエラーが多いのでだれか先輩にciの見方聞いてみてください
おそらく細かい指摘がなくなってお互い幸せになれそう:eyes:
あとはせっかくアロー関数知っているなら全部アロー関数にしちゃいましょう
100knocks内でアロー関数で困るケース無いと思うんで
ペースは良い感じなので引き続き頑張ってください:muscle:

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/03/toBin.html
> +    }
関数ブロックの中はインデントひとつ下げましょう
再代入しない変数にはletではなくconstを使います

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/04/toHex.html
> +    }
上に同じく

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/05/randomBgColor.html
> +</body>
上にあるのでわかっているとは思いますがカラーコードである16進数を作るメソッドはJSに用意されています
バグのもとになるので何か特別な意図がない限りはそっちを使いましょう
頑張ってくれたところ申し訳ないですけども・・・

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/06/bored.html
> +      .innerHTML = '<span class="a">AWESOME</span>';
nits:
これくらいなら改行無いほうが見やすいかな:eyes:

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/07/addImage.html
> +      pi.src = 'img/siwsiw.jpg';
ここもconstですね～
プロパティはいじってますが変数に入れてる物自体を入れ替えてるわけではないので
const zoon = document.getElementByClassName('p')[0];
const pi = document.createElement('img');

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/08/createDiv.html
> +    hako =()=> {
()の前後はスペースが必要です
本来引数を入れる場所なので
const hako = () => {}

nits:
関数名もHakoとかよりもcreateDivとか意味の通じるものにすると良いですね:eyes:
(問題名そのままですけど)

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/09/switch.html
> +                function siwasiwaImage(){
関数()にもスペース必要です
function siwasiwaImage() {}

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/09/switch.html
> +                    let pi = Math.floor(Math.random()*7) + 1;
const～:sob:

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/09/switch.html
> +                };
インデントはスペース４ではなく2ですね～
VSCode indent 設定でググるとこの先幸せになれそう

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/10/3sec.html
> +          setTimeout(function(){
function() {}

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/10/3sec.html
> +        }
；抜けです

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/11/isSame.html
> +              }
上のif(!text || !text) {return}はそれでブロックが閉じられているのでここのインデントは不要です

2019-07-03 14:37 UTC, itti1021 commented on answer/166ryoryo/JS/11/isSame.html
> +            　
不要空行:skull:

2019-07-04 01:23 UTC, itti1021 commented on answer/166ryoryo/JS/07/addImage.html
> +      pi.src = 'img/siwsiw.jpg';
これだと動かないですね～
consoleのエラーを調べてconstの使い方を調べてください

2019-07-04 01:56 UTC, itti1021 requested changes
ちょっと昨日見切れてなかった分もありますが修正お願いします:pray:
please review前に動作確認はして下さいね～

2019-07-04 01:56 UTC, itti1021 commented on answer/166ryoryo/JS/01/wTime.html
> +      const nowMin  = nowTime.getMinutes();
```suggestion
      const nowMin = nowTime.getMinutes();
```

2019-07-04 01:56 UTC, itti1021 commented on answer/166ryoryo/JS/01/wTime.html
> +      const nowSec  = nowTime.getSeconds();
```suggestion
      const nowSec = nowTime.getSeconds();
```

2019-07-04 01:56 UTC, itti1021 commented on answer/166ryoryo/JS/01/wTime.html
> +      const nowSec  = nowTime.getSeconds();
ここ2行スペース余分ですね

2019-07-04 01:56 UTC, itti1021 commented on answer/166ryoryo/JS/05/randomBgColor.html
> +</body>
これciのエラー多すぎて修正難しいんでtoString()使ってください

2019-07-04 01:56 UTC, itti1021 commented on answer/166ryoryo/JS/08/createDiv.html
> +    hako =()=> {
ここの修正がまだです:eyes:

2019-07-04 01:56 UTC, itti1021 commented on answer/166ryoryo/JS/10/3sec.html
> +          setTimeout(function(){
ここも未修正:eyes:

2019-07-04 01:56 UTC, itti1021 commented on answer/166ryoryo/JS/09/switch.html
> +      let pi = Math.floor(Math.random()*7) + 1;
ここもconstです:sob:
基本的にはconst使ってエラー出たり動かなかったらletにする方が良いかもしれませんね

2019-07-04 01:56 UTC, itti1021 commented on answer/166ryoryo/JS/11/isSame.html
> +            if (!text1 || !text2){return}
```suggestion
            if (!text1 || !text2) { return };
```
スペース足りないです

2019-07-04 01:57 UTC, itti1021 commented
> ちょっと昨日見切れてなかった分もありますが修正お願いします🙏

2019-07-04 02:08 UTC, itti1021 commented
間違えてcloseしてしまった

2019-07-04 15:39 UTC, itti1021 requested changes
lintが厳しいので修正多くなってしまいますがめげずに頑張って下さい:sob:

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/01/wTime.html
> +      const msg = "現在時刻は、" + nowHour + ":" + nowMin + ":" + nowSec + " です。";
```suggestion
      const msg =` 現在時刻は、${nowHour}:${nowMin}:${nowSec}です。`;
```
文字と変数の連結にはこれがオススメです
FYI: https://qiita.com/kura07/items/c9fa858870ad56dfec12

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/03/toBin.html
> +    function kazu(){
```suggestion
    function kazu() {
```
function 関数名() {}
　　　　　　　  ↑
関数を書くときはここにスペースが必要です

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/04/toHex.html
> +    function kazu(){
```suggestion
    function kazu() {
```

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/05/randomBgColor.html
> +  function ramdomChgBack()	{
```suggestion
  function ramdomChgBack() {
```
tabではなく半角スペースです

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    document.bgColor = backcolor
```suggestion
    document.bgColor = backcolor;
```
セミコロンがないです

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/05/randomBgColor.html
> +      backcolor += (16*Math.random() | 0).toString(16);
```suggestion
      backcolor += (16 * Math.random() | 0).toString(16);
```
計算の演算子には前後にスペースが必要です

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    for(let i = 0; i < 6; i++) {
```suggestion
    for (let i = 0; i < 6; i++) {
```
forやifの後の()の前にはスペースを入れましょう

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/05/randomBgColor.html
> +</body>
使わない関数等は消しましょう～

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/06/bored.html
> +    document.getElementById("text-button").onclick = function() {
```suggestion
    document.getElementById("text-button").onclick = function () {
```
無名関数を使用する場合は()の前にスペースを入れましょう

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/07/addImage.html
> +      pi.src = 'img/siwsiw.jpg';
よさみあきこです:ok_hand:

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/08/createDiv.html
> +    hako　=()=>{
```suggestion
    hako = () => {
```
スペースを入れる位置が違いますね～

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/09/switch.html
> +
```
switch(pi) {
  case 1:
    img.src = "img/download.jpg";
    break;
```
switch case のインデントはこんな感じです

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/10/3sec.html
> +          setTimeout(function(){
ここの修正お願いします

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/11/isSame.html
> +            if (!text1 || !text2){ return }
```suggestion
            if (!text1 || !text2) { return };
```

2019-07-04 15:39 UTC, itti1021 commented on answer/166ryoryo/JS/11/isSame.html
> +            }　
```suggestion
            }
```
末尾スペースは消しましょう

2019-07-07 06:03 UTC, fumihumi reviewed
> https://circleci.com/gh/ISC-MakeIT/javascript-100knocksV2/312?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

こちらの修正をおねがいできますかー 👀 

- indentがずれているところ
- `()`, `{`, `=`, `+`, `=`, `*`, `/` 等の記号の前後にはスペースを入れる
- 変数の定義には var を使わずに const, letを使う。
    - 基本的に再代入をしない時はconstを使う。

2019-07-08 15:08 UTC, itti1021 commented
ちょっとciの面でエラー多すぎて追えないんで今週の水曜日辺りにciの見方かlintの規定誰か対応しますね:sweat_drops: 
後で修正入るかもしれませんが問題進めててください
一応fumihumi先輩が↑で言っている所を注意してコーディングしてください:bow:

2019-07-18 14:44 UTC, fumihumi commented on answer/166ryoryo/CSS/03/nav.html
> +<meta charset="utf-8">
headタグの中身はインデントしたいですね

2019-07-18 14:44 UTC, fumihumi commented on answer/166ryoryo/JS/01/wTime.html
> +    setInterval('showClock1()', 1000);
`showClock`で良さそう。
関数名に 1, 2 のようなマジックナンバーは明確な意図がない限りやめましょう 👀

2019-07-18 14:44 UTC, fumihumi commented on answer/166ryoryo/JS/03/toBin.html
> +      const suji = parseInt(document.math.elements[0].value);
formの内容を取得するという点では問題なさそうですが、Formの項目が増えた時に `elements[0]`だと対応が大変そうです。

`document.querySelector`を活用してみてください！

2019-07-18 14:44 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    let range = big - small + 1
ifの中でconstで定義しているもの、ここで参照できないような気がする

2019-07-18 14:44 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    if((num1 - num2) > 0)	{
```suggestion
    if((num1 - num2) > 0) {
```

tabではなくスペース使うようにしましょう！

2019-07-18 14:44 UTC, fumihumi commented on answer/166ryoryo/JS/14/storage.js
> +  const i = document.getElementById('language');
使ってないんなら決して良さそう？

2019-07-24 02:48 UTC, fumihumi commented on answer/166ryoryo/HTML/01/hello_Table.html
> +    <td  rowspan="4">こんにちは</td>
```suggestion
    <td rowspan="4">こんにちは</td>
```

2019-07-24 02:48 UTC, fumihumi commented on answer/166ryoryo/JS/06/bored.html
> +    document.getElementById("text-button").onclick = function() {
cc itti 
これ、個人的には 
```
function() {
}
```
でもよいと思ってるのでResolveします

2019-07-24 02:48 UTC, fumihumi commented on answer/166ryoryo/JS/08/createDiv.html
> +    hako　=()=>{
これ

2019-07-24 02:48 UTC, fumihumi commented on answer/166ryoryo/JS/09/switch.html
> +
これも

2019-07-24 02:48 UTC, fumihumi commented on answer/166ryoryo/JS/10/3sec.html
> +        document.getElementById("btn").onclick = function(){
```suggestion
        document.getElementById("btn").onclick = function() {
```

2019-08-06 05:42 UTC, fumihumi reviewed
どうしても、no-unused-varsをDisableにする場合はファイル全体に適応するようにしてください。
今回のコメント修正したら一旦マージしたい（filechangeがひどい）ので追加の問題は可能な限り取り組まないでcIの修正を優先して欲しいです。

2019-08-06 05:42 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    function randomChgBack(num1, num2) {
使ってない関数はけしましょうか

2019-08-06 05:42 UTC, fumihumi commented on answer/166ryoryo/JS/05/randomBgColor.html
> +    function toHex(dec)	{
これも

2019-08-06 05:42 UTC, fumihumi commented on answer/166ryoryo/JS/02/add.js
> +  // eslint-disable-next-line no-console
next-lintじゃなくてファイル全体で無効化した方がよいかも

2019-08-06 05:42 UTC, fumihumi commented on answer/166ryoryo/JS/03/toBin.html
> +      const suji = parseInt(document.math.elements[0].value);
これ見てますか

2019-08-06 05:42 UTC, fumihumi commented on answer/166ryoryo/JS/15/fizzbuzz.js
> +  // eslint-disable-next-line eqeqeq
これはDisableにしないでください。
javascriptにおいて比較を行う際は '=='ではなく、 '==='を使いましょう。

2019-08-06 05:42 UTC, fumihumi commented on answer/166ryoryo/JS/16/array1.js
> +/* eslint-disable eol-last */
これdisableにする必要ある？

2019-08-06 05:42 UTC, fumihumi commented on answer/166ryoryo/JS/16/array1.js
> +/* eslint-disable no-unused-vars */
これも

2019-08-06 05:42 UTC, fumihumi commented on answer/166ryoryo/JS/16/array1.js
> +// eslint-disable-next-line func-names
これもdisableにしなくていい気がする？

2019-08-07 06:46 UTC, fumihumi commented
> answer/166ryoryo/JS/05/randomBgColor.html

これにコメントしてる箇所確認お願いします。

2019-08-07 07:24 UTC, 166ryoryo commented
無効にするより消すべきですか？

2019-08-07 07:32 UTC, fumihumi commented
こんかいeslintをdisableにするのってほとんど無駄だと思っていて、
今回、私やittiが指摘しているのは該当のファイルに使用していない、関数があるという点においてコメントしているので、eslint-disable は意味がないかなと感じています。

2019-08-07 07:55 UTC, fumihumi commented
度々のコメントになってしまい、申し訳ないのですが、

意図が通じているか不明なので改めてコメントします。

> https://github.com/ISC-MakeIT/javascript-100knocksV2/pull/80#discussion_r310887115

未使用の変数をファイル内に定義しておくことはコードを見たときに 
'この関数は定義しているのに実行されていない。いつ使われているんだ？'という疑問の元になるためコメントしました。

ですので、今回して欲しかった対応は
関数定義の前後になぜこの関数を使っていないのに残しているのか理由を明記する。
もしくは記述を削除する、いずれかの対応をして欲しかったという意図になります！
（細かくてすみません。。。。！）

2019-08-09 10:26 UTC, fumihumi commented
CIの修正は別途prにしてください！マージします！

2019-08-09 10:26 UTC, merged