JS途中
ISC-MakeIT/javascript-100knocksV2 pull request #91
Opened 2019-07-10 00:31 UTC by DuGlaser

皆様ありがとうございました！無事プルリクできました

2019-07-12 04:48 UTC, itti1021 reviewed
22だけ修正お願いします:pray:

2019-07-12 04:48 UTC, itti1021 commented on answer/damegane/JS/18.array3/18.html
> +    const tostring = Object.prototype.toString;
nits
このやり方でも要件は満たしますがもっと簡単なやり方もあるので探してみてください

2019-07-12 04:48 UTC, itti1021 commented on answer/damegane/JS/22.rensouhairetu/22.html
> +    });
![image](https://user-images.githubusercontent.com/40228266/61102138-96529900-a4a7-11e9-9c61-597d4362ff05.png)
配列への要素追加が抜けていますね:eyes:

2019-07-15 07:32 UTC, fumihumi reviewed
should とコメントした箇所は修正してもらいたいのでそちらを確認お願いします！
また、Commitメッセージにどの問題を解いたのか含めてもらえるととても助かります！余力があれば試してもらえると！！ 🏹

2019-07-15 07:32 UTC, fumihumi commented on answer/damegane/JS/22.rensouhairetu/22.html
> +    });
> 配列への要素追加が抜けていますね👀

問題なさそうですよ 👀 
cc: itti1021

2019-07-15 07:32 UTC, fumihumi commented on answer/damegane/JS/24.encrypto/24.html
> +    arw = arw.join('');
arwは配列として定義しているのに、joinを使って文字列に変えてしまうと、
arwが配列なのか、文字列なのかがわかりにくいですね。、

この場合 `console.log(arw.join(''))`の方がわかりやすい気がします

2019-07-15 07:32 UTC, fumihumi commented on answer/damegane/JS/25.decrypto/25.html
> +    for (let i = 0; i < ary1.length; i++) {
[should]
cryptで定義した文字列を配列にしなくても
'string'.length, 'string'[n]といった方法で解けそうですね

2019-07-15 07:32 UTC, fumihumi commented on answer/damegane/JS/27.duplicate/27.html
> +        case true:
[should]

switchは複数の条件の時に有用ですが、今回のように `真偽値と比較するだけ` なら
if、もしくは三項演算子の方が読み手に伝わりやすくて良い気がします。

2019-07-19 06:13 UTC, itti1021 commented on answer/damegane/JS/22.rensouhairetu/22.html
> +    });
修正してくれたみたいです・・・！:pray:
コメントってresolveしていった方が良いですかね？

2019-07-19 06:17 UTC, fumihumi commented on answer/damegane/JS/22.rensouhairetu/22.html
> +    });
resolveしましょうか〜

2019-07-19 07:06 UTC, itti1021 requested changes
この段階でここまで来てるのは凄いですね:eyes:
28,29を修正お願いします:pray:

2019-07-19 07:06 UTC, itti1021 commented on answer/damegane/JS/28.dupSort/28.html
> +    const ary = ['10', '3', '25', '6', '5'];
![image](https://user-images.githubusercontent.com/40228266/61515508-be10a680-aa3d-11e9-9013-4f4908a5df7f.png)
少々問題に不備があるので申し訳ないのですが・・・
27の問題を流用してください

2019-07-19 07:06 UTC, itti1021 commented on answer/damegane/JS/29.dupDel/29.html
> +      const ary = ['10', '3', '25', '6', '5'];
こちらも同様にお願いします:pray:

2019-07-19 07:08 UTC, itti1021 commented on answer/damegane/JS/22.rensouhairetu/22.html
> +    });
申し訳ないですー:pray:

2019-07-31 09:41 UTC, fumihumi commented on answer/damegane/JS/23.weather/23.html
> +    const randomNum = Math.ceil(Math.random() * 4 - 1);
```javascript
Math.ceil(Math.random() * 4 - 1)
// => -0
```

こうすると意図してない挙動になる場合がありそう

2019-07-31 09:41 UTC, fumihumi commented on answer/damegane/JS/26.tanuki/26.html
> +    text = text.replace(targetStr1, 'た');
nits: 一度しか使わない場合は変数に入れなくても良さそう

2019-07-31 09:41 UTC, fumihumi commented on answer/damegane/JS/29.dupDel/29.html
> +    const serchAry = () => {
search?

2019-07-31 09:41 UTC, fumihumi commented on answer/damegane/jQuery/05.hasImage/05.html
> +        $('<img src="../04.addImageJq/img/nino.jpg">')
document.createElementとかで作った方が良さそうな気がしました

2019-08-06 05:29 UTC, fumihumi approved these changes
よさそう！

2019-08-06 05:29 UTC, fumihumi commented on answer/damegane/JS/23.weather/23.html
> +      const randomNum = Math.floor(Math.random() * 4);
👍

2019-08-06 05:30 UTC, fumihumi commented
CI~ってお気持ちが無限大ですがFileChangedがしんどいのでまーじします

2019-08-06 05:30 UTC, merged